SELECT * FROM SOR_T_FORNECEDOR FOR UPDATE;

SELECT * FROM SOR_T_SORVETE FOR UPDATE;

SELECT A.NOME SORVETE, B.NOME FORNECEDOR
  FROM SOR_T_SORVETE A, SOR_T_FORNECEDOR B
 WHERE A.IDFORNECEDOR = B.IDFORNECEDOR
