SELECT * FROM SOR_T_SORVETE FOR UPDATE 

SELECT * FROM SOR_T_SORVETE WHERE PRECO > 10

SELECT * FROM SOR_T_SORVETE WHERE PRECO = (SELECT MAX(PRECO) FROM SOR_T_SORVETE)

SELECT NOME FROM SOR_T_SORVETE WHERE DESCRICAO LIKE '%Goiaba%'

SELECT SUM(PRECO) PrecoTotal FROM SOR_T_SORVETE
